/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/floor-1.glb -t 
*/

import { useGLTF } from '@react-three/drei';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
	nodes: {
		Cube: THREE.Mesh;
		Cube003: THREE.Mesh;
		Cube002: THREE.Mesh;
		Cube001: THREE.Mesh;
		Cube004: THREE.Mesh;
		Cube005: THREE.Mesh;
		Cube006: THREE.Mesh;
		Cube007: THREE.Mesh;
		Cube008: THREE.Mesh;
		Cube009: THREE.Mesh;
	};
	materials: {
		['Material.001']: THREE.MeshStandardMaterial;
		['Material.004']: THREE.MeshStandardMaterial;
		['Material.002']: THREE.MeshStandardMaterial;
		['Material.003']: THREE.MeshStandardMaterial;
	};
};

export function Floor1(props: JSX.IntrinsicElements['group']) {
	const { nodes, materials } = useGLTF('/models/floor-1.glb') as GLTFResult;

	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes.Cube.geometry}
				material={materials['Material.001']}
				scale={[0.5, 0.1, 0.5]}
			/>
			<mesh
				geometry={nodes.Cube003.geometry}
				material={materials['Material.004']}
				position={[0.329, 0.1, -0.332]}
				scale={[0.157, 0.012, 0.157]}
			/>
			<mesh
				geometry={nodes.Cube002.geometry}
				material={materials['Material.002']}
				position={[0, 0.1, -0.332]}
				scale={[0.157, 0.012, 0.157]}
			/>
			<mesh
				geometry={nodes.Cube001.geometry}
				material={materials['Material.003']}
				position={[-0.329, 0.1, -0.332]}
				scale={[0.157, 0.012, 0.157]}
			/>
			<mesh
				geometry={nodes.Cube004.geometry}
				material={materials['Material.003']}
				position={[0.329, 0.1, -0.003]}
				scale={[0.157, 0.012, 0.157]}
			/>
			<mesh
				geometry={nodes.Cube005.geometry}
				material={materials['Material.002']}
				position={[0, 0.1, -0.003]}
				scale={[0.157, 0.012, 0.157]}
			/>
			<mesh
				geometry={nodes.Cube006.geometry}
				material={materials['Material.003']}
				position={[-0.329, 0.1, -0.003]}
				scale={[0.157, 0.012, 0.157]}
			/>
			<mesh
				geometry={nodes.Cube007.geometry}
				material={materials['Material.002']}
				position={[0.329, 0.1, 0.326]}
				scale={[0.157, 0.012, 0.157]}
			/>
			<mesh
				geometry={nodes.Cube008.geometry}
				material={materials['Material.003']}
				position={[0, 0.1, 0.326]}
				scale={[0.157, 0.012, 0.157]}
			/>
			<mesh
				geometry={nodes.Cube009.geometry}
				material={materials['Material.004']}
				position={[-0.329, 0.1, 0.326]}
				scale={[0.157, 0.012, 0.157]}
			/>
		</group>
	);
}

useGLTF.preload('/models/floor-1.glb');
