/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/wall-1.glb -t -k 
*/

import { useGLTF } from '@react-three/drei';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
	nodes: {
		Cube: THREE.Mesh;
		Cube001: THREE.Mesh;
		Cube002: THREE.Mesh;
		Cube003: THREE.Mesh;
		Cube004: THREE.Mesh;
		Cube005: THREE.Mesh;
		Cube006: THREE.Mesh;
		Cube007: THREE.Mesh;
		Cube008: THREE.Mesh;
		Cube009: THREE.Mesh;
		Cube010: THREE.Mesh;
		Cube011: THREE.Mesh;
		Cube012: THREE.Mesh;
		Cube013: THREE.Mesh;
	};
	materials: {
		Material: THREE.MeshStandardMaterial;
		['Material.002']: THREE.MeshStandardMaterial;
		['Material.001']: THREE.MeshStandardMaterial;
		['Material.003']: THREE.MeshStandardMaterial;
	};
};

export function Wall1(props: JSX.IntrinsicElements['group']) {
	const { nodes, materials } = useGLTF('/models/wall-1.glb') as GLTFResult;
	return (
		<group {...props} dispose={null}>
			<mesh
				name="Cube"
				geometry={nodes.Cube.geometry}
				material={materials.Material}
				scale={[0.55, 0.75, 0.1]}
			/>
			<mesh
				name="Cube001"
				geometry={nodes.Cube001.geometry}
				material={materials['Material.002']}
				position={[-0.364, 0.62, 0]}
				scale={[0.124, 0.082, 0.121]}
			/>
			<mesh
				name="Cube002"
				geometry={nodes.Cube002.geometry}
				material={materials['Material.001']}
				position={[-0.364, 0.229, 0]}
				scale={[0.124, 0.082, 0.121]}
			/>
			<mesh
				name="Cube003"
				geometry={nodes.Cube003.geometry}
				material={materials['Material.002']}
				position={[-0.364, -0.473, 0]}
				scale={[0.124, 0.082, 0.121]}
			/>
			<mesh
				name="Cube004"
				geometry={nodes.Cube004.geometry}
				material={materials['Material.003']}
				position={[-0.071, -0.365, 0]}
				scale={[0.124, 0.082, 0.121]}
			/>
			<mesh
				name="Cube005"
				geometry={nodes.Cube005.geometry}
				material={materials['Material.003']}
				position={[0.033, 0.517, 0]}
				scale={[0.124, 0.082, 0.121]}
			/>
			<mesh
				name="Cube006"
				geometry={nodes.Cube006.geometry}
				material={materials['Material.001']}
				position={[0.033, -0.625, 0]}
				scale={[0.124, 0.082, 0.121]}
			/>
			<mesh
				name="Cube007"
				geometry={nodes.Cube007.geometry}
				material={materials['Material.002']}
				position={[0.342, -0.226, 0]}
				scale={[0.124, 0.082, 0.121]}
			/>
			<mesh
				name="Cube008"
				geometry={nodes.Cube008.geometry}
				material={materials['Material.003']}
				position={[-0.199, -0.121, 0]}
				scale={[0.124, 0.082, 0.121]}
			/>
			<mesh
				name="Cube009"
				geometry={nodes.Cube009.geometry}
				material={materials['Material.002']}
				position={[0.4, 0.141, 0]}
				scale={[0.124, 0.082, 0.121]}
			/>
			<mesh
				name="Cube010"
				geometry={nodes.Cube010.geometry}
				material={materials['Material.003']}
				position={[0.397, -0.526, 0]}
				scale={[0.124, 0.082, 0.121]}
			/>
			<mesh
				name="Cube011"
				geometry={nodes.Cube011.geometry}
				material={materials['Material.002']}
				position={[0.158, 0.321, 0]}
				scale={[0.124, 0.082, 0.121]}
			/>
			<mesh
				name="Cube012"
				geometry={nodes.Cube012.geometry}
				material={materials['Material.001']}
				position={[0.09, -0.006, 0]}
				scale={[0.124, 0.082, 0.121]}
			/>
			<mesh
				name="Cube013"
				geometry={nodes.Cube013.geometry}
				material={materials['Material.001']}
				position={[0.342, 0.56, 0]}
				scale={[0.124, 0.082, 0.121]}
			/>
		</group>
	);
}

useGLTF.preload('/models/wall-1.glb');
